app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(age = 46)
app$setInputs(sex = "Male")
app$setInputs(cp = "Atypical Angina")
app$setInputs(trestbps = 143)
app$setInputs(chol = 262)
app$setInputs(fbs = "True")
app$setInputs(slope = "flat")
app$setInputs(oldpeak = 1)
app$setInputs(exang = "True")
app$setInputs(thalach = 138)
app$setInputs(restecg = "ST-T wave abnormality")
app$setInputs(thal = "Fixed Defect")
app$setInputs(prediction_button = "click")
app$snapshot()
